APPLY_FIXES: none
VALIDATE_ALL_CODEBASE: false
FILTER_REGEX_EXCLUDE: '(node_modules|dist|coverage|\.github|__pycache__|\.venv)/'

ENABLE_LINTERS:
  - DOCKERFILE_HADOLINT
  - JSON_JSONLINT
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_RUFF
  - REPOSITORY_GITLEAKS
  - REPOSITORY_SECRETLINT
  - REPOSITORY_GIT_DIFF
  - REPOSITORY_TRUFFLEHOG
