sonar.projectKey=colombo-labs_movicol-ai
sonar.organization=colombo-labs
sonar.sources=app,training
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/venv/**
sonar.python.coverage.reportPaths=coverage.xml
